### ISSUE TITLE
[Idea] Schema validation

### ISSUE THREAD

**Issue by koleror** [openwisp/django-flat-json-widget#6]
Hello! 
Thanks for this simple and awesome plugin :) 

It would be nice to be able to provide a json validation schema, to provide more specific errors.
You could use https://python-jsonschema.readthedocs.io/ for that. 

I'd be happy to contribute, if you could point me where I should hook up and the PR has a chance to be merged :)

**Comment by atb00ker** [comment]
I think the validation part needs to be in the form were you are using the widget.

**Comment by koleror** [comment]
Ok, but as the whole json is considered as a single field from the form's point of view, doing so makes it impossible to show errors specific to the json key. An invalid key of value for instance.

**Comment by nemesisdesign** [comment]
@koleror in OpenWISP we use another widget for more complicated JSON structures which has JSON schema validation and UI generation, but we could not finish to extract it as a separate package, it's very tied to openwisp-controller. We had started to work on it but we didn't finish it: https://github.com/openwisp/django-jsonschema-widget/tree/master/django_jsonschema_widget

In this particular widget, I am not sure it's worth adding it for several reasons:

- here we only intend to deal with a flat JSON structure, every member of the JSON object is a string, so the amount of JSON schema features we can use is limited, by using a different solution like the one we use in OpenWISP Controller, which is based on https://github.com/json-editor/json-editor you get the possibility to use any JSON structure you like and the UI is auto-generated, which is nice
-  at least for what concerns OpenWISP, we don't need JSON schema validation in this widget and I do not want to add burden to our few maintainers to maintain this feature in the coming years
 
So I suggest you to either use directly something like https://github.com/json-editor/json-editor or just fork this package and use a forked version of it in which you implement what you need.

There may be other django packages based on https://github.com/json-editor/json-editor, although I'm not sure if they're maintained.  But I recommend double checking.
